name: medsnap-dev
channels:
- conda-forge
dependencies:
- python>=3.10,<3.11
- numpy
- scipy
- pandas
- ipython
- matplotlib
- bokeh
- jupyter
- black
- setuptools
- openpyxl
- pytest
- coverage
- pip
- pip:
  - linecheck
  - geopandas
  - policyengine-us
